import { useState, memo, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faLink} from '@fortawesome/free-solid-svg-icons'

import { parseRestianceCategory, parseMutationType} from 'assets/javascript/formatHelper'
import { nucColors } from 'assets/javascript/sequenceViewerHelper';
import { NumberLine } from 'components/genomeViewer/components/NumberLine';
import { Features } from 'components/genomeViewer/components/Features';
// Stylesheets
import 'assets/styles/tables.css'
import MutationViewer from 'components/genomeViewer/MutationViewer';

const alignment = 'GCCAGCCCCCTGATGGGGGCGACACTCCACCATGAATCACTCCCCTGTGAGGAACTACTGTCTTCACGCAGAAAGCGTCTAGCCATGGCGTTAGTATGAGTGTCGTGCAGCCTCCAGGACCCCCCCTCCCGGGAGAGCCATAGTGGTCTGCGGAACCGGTGAGTACACCGGAATTGCCAGGACGACCGGGTCCTTTCTTGGATAAACCCGCTCAATGCCTGGAGATTTGGGCGTGCCCCCGCAAGACTGCTAGCCGAGTAGTGTTGGGTCGCGAAAGGCCTTGTGGTACTGCCTGATAGGGTGCTTGCGAGTGCCCCGGGAGGTCTCGTAGACCGTGCACCATGAGCACGAATCCTAAACCTCAAAGAAAAACCAAACGTAACACCAACCGTCGCCCACAGGACGTCAAGTTCCCGGGTGGCGGTCAGATCGTTGGTGGAGTTTACTTGTTGCCGCGCAGGGGCCCTAGATTGGGTGTGCGCGCGACGAGGAAGACTTCCGAGCGGTCGCAACCTCGAGGTAGACGTCAGCCTATCCCCAAGGCACGTCGGCCCGAGGGCAGGACCTGGGCTCAGCCCGGGTACCCTTGGCCCCTCTATGGCAATGAGGGTTGCGGGTGGGCGGGATGGCTCCTGTCTCCCCGTGGCTCTCGGCCTAGCTGGGGCCCCACAGACCCCCGGCGTAGGTCGCGCAATTTGGGTAAGGTCATCGATACCCTTACGTGCGGCTTCGCCGACCTCATGGGGTACATACCGCTCGTCGGCGCCCCTCTTGGAGGCGCTGCCAGGGCCCTGGCGCATGGCGTCCGGGTTCTGGAAGACGGCGTGAACTATGCAACAGGGAACCTTCCTGGTTGCTCTTTCTCTATCTTCCTTCTGGCCCTGCTCTCTTGCCTGACTGTGCCCGCTTCAGCCTACCAAGTGCGCAATTCCTCGGGGCTTTACCATGTCACCAATGATTGCCCTAACTCGAGTATTGTGTACGAGGCGGCCGATGCCATCCTGCACACTCCGGGGTGTGTCCCTTGCGTTCGCGAGGGTAACGCCTCGAGGTGTTGGGTGGCGGTGACCCCCACGGTGGCCACCAGGGACGGCAAACTCCCCACAACGCAGCTTCGACGTCATATCGATCTGCTTGTCGGGAGCGCCACCCTCTGCTCGGCCCTCTACGTGGGGGACCTGTGCGGGTCTGTCTTTCTTGTTGGTCAACTGTTTACCTTCTCTCCCAGGCGCCACTGGACGACGCAAGACTGCAATTGTTCTATCTATCCCGGCCATATAACGGGTCATCGCATGGCATGGGATATGATGATGAACTGGTCCCCTACGGCAGCGTTGGTGGTAGCTCAGCTGCTCCGGATCCCACAAGCCATCATGGACATGATCGCTGGTGCTCACTGGGGAGTCCTGGCGGGCATAGCGTATTTCTCCATGGTGGGGAACTGGGCGAAGGTCCTGGTAGTGCTGCTGCTATTTGCCGGCGTCGACGCGGAAACCCACGTCACCGGGGGAAGTGCCGGCCGCACCACGGCTGGGCTTGTTGGTCTCCTTACACCAGGCGCCAAGCAGAACATCCAACTGATCAACACCAACGGCAGTTGGCACATCAATAGCACGGCCTTGAACTGCAATGAAAGCCTTAACACCGGCTGGTTAGCAGGGCTCTTCTATCAGCACAAATTCAACTCTTCAGGCTGTCCTGAGAGGTTGGCCAGCTGCCGACGCCTTACCGATTTTGCCCAGGGCTGGGGTCCTATCAGTTATGCCAACGGAAGCGGCCTCGACGAACGCCCCTACTGCTGGCACTACCCTCCAAGACCTTGTGGCATTGTGCCCGCAAAGAGCGTGTGTGGCCCGGTATATTGCTTCACTCCCAGCCCCGTGGTGGTGGGAACGACCGACAGGTCGGGCGCGCCTACCTACAGCTGGGGTGCAAATGATACGGATGTCTTCGTCCTTAACAACACCAGGCCACCGCTGGGCAATTGGTTCGGTTGTACCTGGATGAACTCAACTGGATTCACCAAAGTGTGCGGAGCGCCCCCTTGTGTCATCGGAGGGGTGGGCAACAACACCTTGCTCTGCCCCACTGATTGTTTCCGCAAGCATCCGGAAGCCACATACTCTCGGTGCGGCTCCGGTCCCTGGATTACACCCAGGTGCATGGTCGACTACCCGTATAGGCTTTGGCACTATCCTTGTACCATCAATTACACCATATTCAAAGTCAGGATGTACGTGGGAGGGGTCGAGCACAGGCTGGAAGCGGCCTGCAACTGGACGCGGGGCGAACGCTGTGATCTGGAAGACAGGGACAGGTCCGAGCTCAGCCCATTGCTGCTGTCCACCACACAGTGGCAGGTCCTTCCGTGTTCTTTCACGACCCTGCCAGCCTTGTCCACCGGCCTCATCCACCTCCACCAGAACATTGTGGACGTGCAGTACTTGTACGGGGTAGGGTCAAGCATCGCGTCCTGGGCCATTAAGTGGGAGTACGTCGTTCTCCTGTTCCTCCTGCTTGCAGACGCGCGCGTCTGCTCCTGCTTGTGGATGATGTTACTCATATCCCAAGCGGAGGCGGCTTTGGAGAACCTCGTAATACTCAATGCAGCATCCCTGGCCGGGACGCACGGTCTTGTGTCCTTCCTCGTGTTCTTCTGCTTTGCGTGGTATCTGAAGGGTAGGTGGGTGCCCGGAGCGGTCTACGCCTTCTACGGGATGTGGCCTCTCCTCCTGCTCCTGCTGGCGTTGCCTCAGCGGGCATACGCACTGGACACGGAGGTGGCCGCGTCGTGTGGCGGCGTTGTTCTTGTCGGGTTAATGGCGCTGACTCTGTCGCCATATTACAAGCGCTACATCAGCTGGTGCATGTGGTGGCTTCAGTATTTTCTGACCAGAGTAGAAGCGCAACTGCACGTGTGGGTTCCCCCCCTCAACGTCCGGGGGGGGCGCGATGCCGTCATCTTACTCATGTGTGTTGTACACCCGACTCTGGTATTTGACATCACCAAACTACTCCTGGCCATCTTCGGACCCCTTTGGATTCTTCAAGCCAGTTTGCTTAAAGTCCCCTACTTCGTGCGCGTTCAAGGCCTTCTCCGGATCTGCGCGCTAGCGCGGAAGATAGCCGGAGGTCATTACGTGCAAATGGCCATCATCAAGTTAGGGGCGCTTACTGGCACCTATGTGTATAACCATCTCACCCCTCTTCGAGACTGGGCGCACAACGGCCTGCGAGATCTGGCCGTGGCTGTGGAACCAGTCGTCTTCTCCCGAATGGAGACCAAGCTCATCACGTGGGGGGCAGATACCGCCGCGTGCGGTGACATCATCAACGGCTTGCCCGTCTCTGCCCGTAGGGGCCAGGAGATACTGCTTGGGCCAGCCGACGGAATGGTCTCCAAGGGGTGGAGGTTGCTGGCGCCCATCACGGCGTACGCCCAGCAGACGAGAGGCCTCCTAGGGTGTATAATCACCAGCCTGACTGGCCGGGACAAAAACCAAGTGGAGGGTGAGGTCCAGATCGTGTCAACTGCTACCCAAACCTTCCTGGCAACGTGCATCAATGGGGTATGCTGGACTGTCTACCACGGGGCCGGAACGAGGACCATCGCATCACCCAAGGGTCCTGTCATCCAGATGTATACCAATGTGGACCAAGACCTTGTGGGCTGGCCCGCTCCTCAAGGTTCCCGCTCATTGACACCCTGCACCTGCGGCTCCTCGGACCTTTACCTGGTCACGAGGCACGCCGATGTCATTCCCGTGCGCCGGCGAGGTGATAGCAGGGGTAGCCTGCTTTCGCCCCGGCCCATTTCCTACTTGAAAGGCTCCTCGGGGGGTCCGCTGTTGTGCCCCGCGGGACACGCCGTGGGCCTATTCAGGGCCGCGGTGTGCACCCGTGGAGTGGCTAAGGCGGTGGACTTTATCCCTGTGGAGAACCTAGAGACAACCATGAGATCCCCGGTGTTCACGGACAACTCCTCTCCACCAGCAGTGCCCCAGAGCTTCCAGGTGGCCCACCTGCATGCTCCCACCGGCAGCGGTAAGAGCACCAAGGTCCCGGCTGCGTACGCAGCCCAGGGCTACAAGGTGTTGGTGCTCAACCCCTCTGTTGCTGCAACGCTGGGCTTTGGTGCTTACATGTCCAAGGCCCATGGGGTTGATCCTAATATCAGGACCGGGGTGAGAACAATTACCACTGGCAGCCCCATCACGTACTCCACCTACGGCAAGTTCCTTGCCGACGGCGGGTGCTCAGGAGGTGCTTATGACATAATAATTTGTGACGAGTGCCACTCCACGGATGCCACATCCATCTTGGGCATCGGCACTGTCCTTGACCAAGCAGAGACTGCGGGGGCGAGACTGGTTGTGCTCGCCACTGCTACCCCTCCGGGCTCCGTCACTGTGTCCCATCCTAACATCGAGGAGGTTGCTCTGTCCACCACCGGAGAGATCCCTTTTTACGGCAAGGCTATCCCCCTCGAGGTGATCAAGGGGGGAAGACATCTCATCTTCTGCCACTCAAAGAAGAAGTGCGACGAGCTCGCCGCGAAGCTGGTCGCATTGGGCATCAATGCCGTGGCCTACTACCGCGGTCTTGACGTGTCTGTCATCCCGACCAGCGGCGATGTTGTCGTCGTGTCGACCGATGCTCTCATGACTGGCTTTACCGGCGACTTCGACTCTGTGATAGACTGCAACACGTGTGTCACTCAGACAGTCGATTTCAGCCTTGACCCTACCTTTACCATTGAGACAACCACGCTCCCCCAGGATGCTGTCTCCAGGACTCAACGCCGGGGCAGGACTGGCAGGGGGAAGCCAGGCATCTACAGATTTGTGGCACCGGGGGAGCGCCCCTCCGGCATGTTCGACTCGTCCGTCCTCTGTGAGTGCTATGACGCGGGCTGTGCTTGGTATGAGCTCACGCCCGCCGAGACTACAGTTAGGCTACGAGCGTACATGAACACCCCGGGGCTTCCCGTGTGCCAGGACCATCTTGAATTTTGGGAGGGCGTCTTTACGGGCCTCACTCATATAGATGCCCACTTTCTATCCCAGACAAAGCAGAGTGGGGAGAACTTTCCTTACCTGGTAGCGTACCAAGCCACCGTGTGCGCTAGGGCTCAAGCCCCTCCCCCATCGTGGGACCAGATGTGGAAGTGTTTGATCCGCCTTAAACCCACCCTCCATGGGCCAACACCCCTGCTATACAGACTGGGCGCTGTTCAGAATGAAGTCACCCTGACGCACCCAATCACCAAATACATCATGACATGCATGTCGGCCGACCTGGAGGTCGTCACGAGCACCTGGGTGCTCGTTGGCGGCGTCCTGGCTGCTCTGGCCGCGTATTGCCTGTCAACAGGCTGCGTGGTCATAGTGGGCAGGATTGTCTTGTCCGGGAAGCCGGCAATTATACCTGACAGGGAGGTTCTCTACCAGGAGTTCGATGAGATGGAAGAGTGCTCTCAGCACTTACCGTACATCGAGCAAGGGATGATGCTCGCTGAGCAGTTCAAGCAGAAGGCCCTCGGCCTCCTGCAGACCGCGTCCCGCCAAGCAGAGGTTATCACCCCTGCTGTCCAGACCAACTGGCAGAAACTCGAGGTCTTCTGGGCGAAGCACATGTGGAATTTCATCAGTGGGATACAATACTTGGCGGGCCTGTCAACGCTGCCTGGTAACCCCGCCATTGCTTCATTGATGGCTTTTACAGCTGCCGTCACCAGCCCACTAACCACTGGCCAAACCCTCCTCTTCAACATATTGGGGGGGTGGGTGGCTGCCCAGCTCGCCGCCCCCGGTGCCGCTACCGCCTTTGTGGGCGCTGGCTTAGCTGGCGCCGCCATCGGCAGCGTTGGACTGGGGAAGGTCCTCGTGGACATTCTTGCAGGGTATGGCGCGGGCGTGGCGGGAGCTCTTGTAGCATTCAAGATCATGAGCGGTGAGGTCCCCTCCACGGAGGACCTGGTCAATCTGCTGCCCGCCATCCTCTCGCCTGGAGCCCTTGTAGTCGGTGTGGTCTGCGCAGCAATACTGCGCCGGCACGTTGGCCCGGGCGAGGGGGCAGTGCAATGGATGAACCGGCTAATAGCCTTCGCCTCCCGGGGGAACCATGTTTCCCCCACGCACTACGTGCCGGAGAGCGATGCAGCCGCCCGCGTCACTGCCATACTCAGCAGCCTCACTGTAACCCAGCTCCTGAGGCGACTGCATCAGTGGATAAGCTCGGAGTGTACCACTCCATGCTCCGGTTCCTGGCTAAGGGACATCTGGGACTGGATATGCGAGGTGCTGAGCGACTTTAAGACCTGGCTGAAAGCCAAGCTCATGCCACAACTGCCTGGGATTCCCTTTGTGTCCTGCCAGCGCGGGTATAGGGGGGTCTGGCGAGGAGACGGCATTATGCACACTCGCTGCCACTGTGGAGCTGAGATCACTGGACATGTCAAAAACGGGACGATGAGGATCGTCGGTCCTAGGACCTGCAGGAACATGTGGAGTGGGACGTTCCCCATTAACGCCTACACCACGGGCCCCTGTACTCCCCTTCCTGCGCCGAACTATAAGTTCGCGCTGTGGAGGGTGTCTGCAGAGGAATACGTGGAGATAAGGCGGGTGGGGGACTTCCACTACGTATCGGGTATGACTACTGACAATCTTAAATGCCCGTGCCAGATCCCATCGCCCGAATTTTTCACAGAATTGGACGGGGTGCGCCTACATAGGTTTGCGCCCCCTTGCAAGCCCTTGCTGCGGGAGGAGGTATCATTCAGAGTAGGACTCCACGAGTACCCGGTGGGGTCGCAATTACCTTGCGAGCCCGAACCGGACGTAGCCGTGTTGACGTCCATGCTCACTGATCCCTCCCATATAACAGCAGAGGCGGCCGGGAGAAGGTTGGCGAGAGGGTCACCCCCTTCTATGGCCAGCTCCTCGGCCAGCCAGCTGTCCGCTCCATCTCTCAAGGCAACTTGCACCGCCAACCATGACTCCCCTGACGCCGAGCTCATAGAGGCTAACCTCCTGTGGAGGCAGGAGATGGGCGGCAACATCACCAGGGTTGAGTCAGAGAACAAAGTGGTGATTCTGGACTCCTTCGATCCGCTTGTGGCAGAGGAGGATGAGCGGGAGGTCTCCGTACCCGCAGAAATTCTGCGGAAGTCTCGGAGATTCGCCCGGGCCCTGCCCGTTTGGGCGCGGCCGGACTACAACCCCCCGCTAGTAGAGACGTGGAAAAAGCCTGACTACGAACCACCTGTGGTCCATGGCTGCCCGCTACCACCTCCACGGTCCCCTCCTGTGCCTCCGCCTCGGAAAAAGCGTACGGTGGTCCTCACCGAATCAACCCTATCTACTGCCTTGGCCGAGCTTGCCACCAAAAGTTTTGGCAGCTCCTCAACTTCCGGCATTACGGGCGACAATACGACAACATCCTCTGAGCCCGCCCCTTCTGGCTGCCCCCCCGACTCCGACGTTGAGTCCTATTCTTCCATGCCCCCCCTGGAGGGGGAGCCTGGGGATCCGGATCTCAGCGACGGGTCATGGTCGACGGTCAGTAGTGGGGCCGACACGGAAGATGTCGTGTGCTGCTCAATGTCTTATTCCTGGACAGGCGCACTCGTCACCCCGTGCGCTGCGGAAGAACAAAAACTGCCCATCAACGCACTGAGCAACTCGTTGCTACGCCATCACAATCTGGTGTATTCCACCACTTCACGCAGTGCTTGCCAAAGGCAGAAGAAAGTCACATTTGACAGACTGCAAGTTCTGGACAGCCATTACCAGGACGTGCTCAAGGAGGTCAAAGCAGCGGCGTCAAAAGTGAAGGCTAACTTGCTATCCGTAGAGGAAGCTTGCAGCCTGACGCCCCCACATTCAGCCAAATCCAAGTTTGGCTATGGGGCAAAAGACGTCCGTTGCCATGCCAGAAAGGCCGTAGCCCACATCAACTCCGTGTGGAAAGACCTTCTGGAAGACAGTGTAACACCAATAGACACTACCATCATGGCCAAGAACGAGGTTTTCTGCGTTCAGCCTGAGAAGGGGGGTCGTAAGCCAGCTCGTCTCATCGTGTTCCCCGACCTGGGCGTGCGCGTGTGCGAGAAGATGGCCCTGTACGACGTGGTTAGCAAGCTCCCCCTGGCCGTGATGGGAAGCTCCTACGGATTCCAATACTCACCAGGACAGCGGGTTGAATTCCTCGTGCAAGCGTGGAAGTCCAAGAAGACCCCGATGGGGTTCTCGTATGATACCCGCTGTTTTGACTCCACAGTCACTGAGAGCGACATCCGTACGGAGGAGGCAATTTACCAATGTTGTGACCTGGACCCCCAAGCCCGCGTGGCCATCAAGTCCCTCACTGAGAGGCTTTATGTTGGGGGCCCTCTTACCAATTCAAGGGGGGAAAACTGCGGCTACCGCAGGTGCCGCGCGAGCGGCGTACTGACAACTAGCTGTGGTAACACCCTCACTTGCTACATCAAGGCCCGGGCAGCCTGTCGAGCCGCAGGGCTCCAGGACTGCACCATGCTCGTGTGTGGCGACGACTTAGTCGTTATCTGTGAAAGTGCGGGGGTCCAGGAGGACGCGGCGAGCCTGAGAGCCTTCACGGAGGCTATGACCAGGTACTCCGCCCCCCCCGGGGACCCCCCACAACCAGAATACGACTTGGAGCTTATAACATCATGCTCCTCCAACGTGTCAGTCGCCCACGACGGCGCTGGAAAGAGGGTCTACTACCTTACCCGTGACCCTACAACCCCCCTCGCGAGAGCCGCGTGGGAGACAGCAAGACACACTCCAGTCAATTCCTGGCTAGGCAACATAATCATGTTTGCCCCCACACTGTGGGCGAGGATGATACTGATGACCCATTTCTTTAGCGTCCTCATAGCCAGGGATCAGCTTGAACAGGCTCTTAACTGTGAGATCTACGGAGCCTGCTACTCCATAGAACCACTGGATCTACCTCCAATCATTCAAAGACTCCATGGCCTCAGCGCATTTTCACTCCACAGTTACTCTCCAGGTGAAATCAATAGGGTGGCCGCATGCCTCAGAAAACTTGGGGTCCCGCCCTTGCGAGCTTGGAGACACCGGGCCCGGAGCGTCCGCGCTAGGCTTCTGTCCAGAGGAGGCAGGGCTGCCATATGTGGCAAGTACCTCTTCAACTGGGCAGTAAGAACAAAGCTCAAACTCACTCCAATAGCGGCCGCTGGCCGGCTGGACTTGTCCGGTTGGTTCACGGCTGGCTACAGCGGGGGAGACATTTATCACAGCGTGTCTCATGCCCGGCCCCGCTGGTTCTGGTTTTGCCTACTCCTGCTCGCTGCAGGGGTAGGCATCTACCTCCTCCCCAACCGATGAAGGTTGGGGTAAACACTCCGGCCTCTTAGGCCATTTCCTGTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTCTTTTTTTTTTTTTTTTTCCTTTTTTTTTTTTTTTTTTTTCTTTCCTTCTTTTTTCCTTTCTTTTCCTTCCTTCTTTAATGGTGGCTCCATCTTAGCCCTAGTCACGGCTAGCTGTGAAAGGTCCGTGAGCCGCATGACTGCAGAGAGTGCTGATACTGGCCTCTCTGCAGATCATGT'

const features = [
                    // {cds_start:342,	cds_end:914,	product:'core protein'},
                    // {cds_start:915,	cds_end:	1490,	product:'envelope protein E1'},
                    // {cds_start:1491,	cds_end:	2579,	product:'envelope protein E2'},
                    // {cds_start:2580,	cds_end:	2768,	product:'protein p7'},
                    // {cds_start:2769,	cds_end:	3419,	product:'nonstructural protein NS2'},
                    {cds_start:3420,	cds_end:	5312,	product:'protease/helicase protein NS3', gene:'NS3'},
                    // {cds_start:5313,	cds_end:	5474,	product:'nonstructural protein NS4A'},
                    // {cds_start:5475,	cds_end:	6257,	product:'nonstructural protein NS4B'},
                    {cds_start:6258,	cds_end:	7601,	product:'nonstructural protein NS5A', gene:'NS5A'},
                    {cds_start:7602,	cds_end:	9374,	product:'RNA-dependent RNA polymerase NS5B', gene:'NS5B'}
                ]

const PolymorphismsVisual = ( { data=null, type=null } ) => {

    const [selectedFeature, setSelectedFeature] = useState(null);
    const [selectedPolymorphism, setSelectedPolymorphisms] = useState(null)
    useEffect(() => {
        if (data?.length && features.length) {
            onFeatureClick(0); // load first feature
        }
    }, [data]);

    if (!Array.isArray(data) || data.length === 0) {
        return <div>No data found...</div>; // or a loader / empty state
    }

    
    const min = 1;
    const max = alignment.length;
    const range = max - min;
    const positions_tmp = Array.from(new Set([].concat(...features.map(f => [f.cds_start])))).sort((a, b) => a - b);
    const positions = [min, ...positions_tmp, max]

    

    const onFeatureClick = (feature) => {
        const polys = data.filter(polymorphism => polymorphism.protein_name == features[feature].gene)
        setSelectedPolymorphisms(polys)
        setSelectedFeature(features[feature])
    }


    return (
        <div>
            <NumberLine positions={positions} min={min} range={range} includeLabel={false}/>
            <Features
                features={features}
                min={min}
                range={range}
                selectedFeature={selectedFeature}
                setSelectedFeature={onFeatureClick}
                includeLabel={false}
            />

            {selectedFeature && (
                <div className='selected-feature'>
                    <h5 className='selected-feature-label'>{selectedFeature.product} ({selectedFeature.cds_start} - {selectedFeature.cds_end})</h5>
                    <MutationViewer  
                        reference_sequence={alignment} 
                        mutations={selectedPolymorphism}
                        start={parseInt(selectedFeature.cds_start)}
                        end={parseInt(selectedFeature.cds_end)}
                    />
                    
                </div>
            )}

        </div>

    );
};

export default PolymorphismsVisual;
