import { useState, memo } from 'react';
import { Link } from 'react-router-dom';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faLink} from '@fortawesome/free-solid-svg-icons'

import { parseRestianceCategory, parseMutationType} from 'assets/javascript/formatHelper'
import { nucColors } from 'assets/javascript/sequenceViewerHelper';
import { NumberLine } from 'components/genomeViewer/components/NumberLine';
import { Features } from 'components/genomeViewer/components/Features';
// Stylesheets
import 'assets/styles/tables.css'
import MutationViewer from 'components/genomeViewer/MutationViewer';

const alignment = 'GCCAGCCCCCTGATGGGGGCGACACTCCACCATGAATCACTCCCCTGTGAGGAACTACTGTCTTCACGCAGAAAGCGTCTAGCCATGGCGTTAGTATGAGTGTCGTGCAGCCTCCAGGACCCCCCCTCCCGGGAGAGCCATAGTGGTCTGCGGAACCGGTGAGTACACCGGAATTGCCAGGACGACCGGGTCCTTTCTTGGATAAACCCGCTCAATGCCTGGAGATTTGGGCGTGCCCCCGCAAGACTGCTAGCCGAGTAGTGTTGGGTCGCGAAAGGCCTTGTGGTACTGCCTGATAGGGTGCTTGCGAGTGCCCCGGGAGGTCTCGTAGACCGTGCACCATGAGCACGAATCCTAAACCTCAAAGAAAAACCAAACGTAACACCAACCGTCGCCCACAGGACGTCAAGTTCCCGGGTGGCGGTCAGATCGTTGGTGGAGTTTACTTGTTGCCGCGCAGGGGCCCTAGATTGGGTGTGCGCGCGACGAGGAAGACTTCCGAGCGGTCGCAACCTCGAGGTAGACGTCAGCCTATCCCCAAGGCACGTCGGCCCGAGGGCAGGACCTGGGCTCAGCCCGGGTACCCTTGGCCCCTCTATGGCAATGAGGGTTGCGGGTGGGCGGGATGGCTCCTGTCTCCCCGTGGCTCTCGGCCTAGCTGGGGCCCCACAGACCCCCGGCGTAGGTCGCGCAATTTGGGTAAGGTCATCGATACCCTTACGTGCGGCTTCGCCGACCTCATGGGGTACATACCGCTCGTCGGCGCCCCTCTTGGAGGCGCTGCCAGGGCCCTGGCGCATGGCGTCCGGGTTCTGGAAGACGGCGTGAACTATGCAACAGGGAACCTTCCTGGTTGCTCTTTCTCTATCTTCCTTCTGGCCCTGCTCTCTTGCCTGACTGTGCCCGCTTCAGCCTACCAAGTGCGCAATTCCTCGGGGCTTTACCATGTCACCAATGATTGCCCTAACTCGAGTATTGTGTACGAGGCGGCCGATGCCATCCTGCACACTCCGGGGTGTGTCCCTTGCGTTCGCGAGGGTAACGCCTCGAGGTGTTGGGTGGCGGTGACCCCCACGGTGGCCACCAGGGACGGCAAACTCCCCACAACGCAGCTTCGACGTCATATCGATCTGCTTGTCGGGAGCGCCACCCTCTGCTCGGCCCTCTACGTGGGGGACCTGTGCGGGTCTGTCTTTCTTGTTGGTCAACTGTTTACCTTCTCTCCCAGGCGCCACTGGACGACGCAAGACTGCAATTGTTCTATCTATCCCGGCCATATAACGGGTCATCGCATGGCATGGGATATGATGATGAACTGGTCCCCTACGGCAGCGTTGGTGGTAGCTCAGCTGCTCCGGATCCCACAAGCCATCATGGACATGATCGCTGGTGCTCACTGGGGAGTCCTGGCGGGCATAGCGTATTTCTCCATGGTGGGGAACTGGGCGAAGGTCCTGGTAGTGCTGCTGCTATTTGCCGGCGTCGACGCGGAAACCCACGTCACCGGGGGAAGTGCCGGCCGCACCACGGCTGGGCTTGTTGGTCTCCTTACACCAGGCGCCAAGCAGAACATCCAACTGATCAACACCAACGGCAGTTGGCACATCAATAGCACGGCCTTGAACTGCAATGAAAGCCTTAACACCGGCTGGTTAGCAGGGCTCTTCTATCAGCACAAATTCAACTCTTCAGGCTGTCCTGAGAGGTTGGCCAGCTGCCGACGCCTTACCGATTTTGCCCAGGGCTGGGGTCCTATCAGTTATGCCAACGGAAGCGGCCTCGACGAACGCCCCTACTGCTGGCACTACCCTCCAAGACCTTGTGGCATTGTGCCCGCAAAGAGCGTGTGTGGCCCGGTATATTGCTTCACTCCCAGCCCCGTGGTGGTGGGAACGACCGACAGGTCGGGCGCGCCTACCTACAGCTGGGGTGCAAATGATACGGATGTCTTCGTCCTTAACAACACCAGGCCACCGCTGGGCAATTGGTTCGGTTGTACCTGGATGAACTCAACTGGATTCACCAAAGTGTGCGGAGCGCCCCCTTGTGTCATCGGAGGGGTGGGCAACAACACCTTGCTCTGCCCCACTGATTGTTTCCGCAAGCATCCGGAAGCCACATACTCTCGGTGCGGCTCCGGTCCCTGGATTACACCCAGGTGCATGGTCGACTACCCGTATAGGCTTTGGCACTATCCTTGTACCATCAATTACACCATATTCAAAGTCAGGATGTACGTGGGAGGGGTCGAGCACAGGCTGGAAGCGGCCTGCAACTGGACGCGGGGCGAACGCTGTGATCTGGAAGACAGGGACAGGTCCGAGCTCAGCCCATTGCTGCTGTCCACCACACAGTGGCAGGTCCTTCCGTGTTCTTTCACGACCCTGCCAGCCTTGTCCACCGGCCTCATCCACCTCCACCAGAACATTGTGGACGTGCAGTACTTGTACGGGGTAGGGTCAAGCATCGCGTCCTGGGCCATTAAGTGGGAGTACGTCGTTCTCCTGTTCCTCCTGCTTGCAGACGCGCGCGTCTGCTCCTGCTTGTGGATGATGTTACTCATATCCCAAGCGGAGGCGGCTTTGGAGAACCTCGTAATACTCAATGCAGCATCCCTGGCCGGGACGCACGGTCTTGTGTCCTTCCTCGTGTTCTTCTGCTTTGCGTGGTATCTGAAGGGTAGGTGGGTGCCCGGAGCGGTCTACGCCTTCTACGGGATGTGGCCTCTCCTCCTGCTCCTGCTGGCGTTGCCTCAGCGGGCATACGCACTGGACACGGAGGTGGCCGCGTCGTGTGGCGGCGTTGTTCTTGTCGGGTTAATGGCGCTGACTCTGTCGCCATATTACAAGCGCTACATCAGCTGGTGCATGTGGTGGCTTCAGTATTTTCTGACCAGAGTAGAAGCGCAACTGCACGTGTGGGTTCCCCCCCTCAACGTCCGGGGGGGGCGCGATGCCGTCATCTTACTCATGTGTGTTGTACACCCGACTCTGGTATTTGACATCACCAAACTACTCCTGGCCATCTTCGGACCCCTTTGGATTCTTCAAGCCAGTTTGCTTAAAGTCCCCTACTTCGTGCGCGTTCAAGGCCTTCTCCGGATCTGCGCGCTAGCGCGGAAGATAGCCGGAGGTCATTACGTGCAAATGGCCATCATCAAGTTAGGGGCGCTTACTGGCACCTATGTGTATAACCATCTCACCCCTCTTCGAGACTGGGCGCACAACGGCCTGCGAGATCTGGCCGTGGCTGTGGAACCAGTCGTCTTCTCCCGAATGGAGACCAAGCTCATCACGTGGGGGGCAGATACCGCCGCGTGCGGTGACATCATCAACGGCTTGCCCGTCTCTGCCCGTAGGGGCCAGGAGATACTGCTTGGGCCAGCCGACGGAATGGTCTCCAAGGGGTGGAGGTTGCTGGCGCCCATCACGGCGTACGCCCAGCAGACGAGAGGCCTCCTAGGGTGTATAATCACCAGCCTGACTGGCCGGGACAAAAACCAAGTGGAGGGTGAGGTCCAGATCGTGTCAACTGCTACCCAAACCTTCCTGGCAACGTGCATCAATGGGGTATGCTGGACTGTCTACCACGGGGCCGGAACGAGGACCATCGCATCACCCAAGGGTCCTGTCATCCAGATGTATACCAATGTGGACCAAGACCTTGTGGGCTGGCCCGCTCCTCAAGGTTCCCGCTCATTGACACCCTGCACCTGCGGCTCCTCGGACCTTTACCTGGTCACGAGGCACGCCGATGTCATTCCCGTGCGCCGGCGAGGTGATAGCAGGGGTAGCCTGCTTTCGCCCCGGCCCATTTCCTACTTGAAAGGCTCCTCGGGGGGTCCGCTGTTGTGCCCCGCGGGACACGCCGTGGGCCTATTCAGGGCCGCGGTGTGCACCCGTGGAGTGGCTAAGGCGGTGGACTTTATCCCTGTGGAGAACCTAGAGACAACCATGAGATCCCCGGTGTTCACGGACAACTCCTCTCCACCAGCAGTGCCCCAGAGCTTCCAGGTGGCCCACCTGCATGCTCCCACCGGCAGCGGTAAGAGCACCAAGGTCCCGGCTGCGTACGCAGCCCAGGGCTACAAGGTGTTGGTGCTCAACCCCTCTGTTGCTGCAACGCTGGGCTTTGGTGCTTACATGTCCAAGGCCCATGGGGTTGATCCTAATATCAGGACCGGGGTGAGAACAATTACCACTGGCAGCCCCATCACGTACTCCACCTACGGCAAGTTCCTTGCCGACGGCGGGTGCTCAGGAGGTGCTTATGACATAATAATTTGTGACGAGTGCCACTCCACGGATGCCACATCCATCTTGGGCATCGGCACTGTCCTTGACCAAGCAGAGACTGCGGGGGCGAGACTGGTTGTGCTCGCCACTGCTACCCCTCCGGGCTCCGTCACTGTGTCCCATCCTAACATCGAGGAGGTTGCTCTGTCCACCACCGGAGAGATCCCTTTTTACGGCAAGGCTATCCCCCTCGAGGTGATCAAGGGGGGAAGACATCTCATCTTCTGCCACTCAAAGAAGAAGTGCGACGAGCTCGCCGCGAAGCTGGTCGCATTGGGCATCAATGCCGTGGCCTACTACCGCGGTCTTGACGTGTCTGTCATCCCGACCAGCGGCGATGTTGTCGTCGTGTCGACCGATGCTCTCATGACTGGCTTTACCGGCGACTTCGACTCTGTGATAGACTGCAACACGTGTGTCACTCAGACAGTCGATTTCAGCCTTGACCCTACCTTTACCATTGAGACAACCACGCTCCCCCAGGATGCTGTCTCCAGGACTCAACGCCGGGGCAGGACTGGCAGGGGGAAGCCAGGCATCTACAGATTTGTGGCACCGGGGGAGCGCCCCTCCGGCATGTTCGACTCGTCCGTCCTCTGTGAGTGCTATGACGCGGGCTGTGCTTGGTATGAGCTCACGCCCGCCGAGACTACAGTTAGGCTACGAGCGTACATGAACACCCCGGGGCTTCCCGTGTGCCAGGACCATCTTGAATTTTGGGAGGGCGTCTTTACGGGCCTCACTCATATAGATGCCCACTTTCTATCCCAGACAAAGCAGAGTGGGGAGAACTTTCCTTACCTGGTAGCGTACCAAGCCACCGTGTGCGCTAGGGCTCAAGCCCCTCCCCCATCGTGGGACCAGATGTGGAAGTGTTTGATCCGCCTTAAACCCACCCTCCATGGGCCAACACCCCTGCTATACAGACTGGGCGCTGTTCAGAATGAAGTCACCCTGACGCACCCAATCACCAAATACATCATGACATGCATGTCGGCCGACCTGGAGGTCGTCACGAGCACCTGGGTGCTCGTTGGCGGCGTCCTGGCTGCTCTGGCCGCGTATTGCCTGTCAACAGGCTGCGTGGTCATAGTGGGCAGGATTGTCTTGTCCGGGAAGCCGGCAATTATACCTGACAGGGAGGTTCTCTACCAGGAGTTCGATGAGATGGAAGAGTGCTCTCAGCACTTACCGTACATCGAGCAAGGGATGATGCTCGCTGAGCAGTTCAAGCAGAAGGCCCTCGGCCTCCTGCAGACCGCGTCCCGCCAAGCAGAGGTTATCACCCCTGCTGTCCAGACCAACTGGCAGAAACTCGAGGTCTTCTGGGCGAAGCACATGTGGAATTTCATCAGTGGGATACAATACTTGGCGGGCCTGTCAACGCTGCCTGGTAACCCCGCCATTGCTTCATTGATGGCTTTTACAGCTGCCGTCACCAGCCCACTAACCACTGGCCAAACCCTCCTCTTCAACATATTGGGGGGGTGGGTGGCTGCCCAGCTCGCCGCCCCCGGTGCCGCTACCGCCTTTGTGGGCGCTGGCTTAGCTGGCGCCGCCATCGGCAGCGTTGGACTGGGGAAGGTCCTCGTGGACATTCTTGCAGGGTATGGCGCGGGCGTGGCGGGAGCTCTTGTAGCATTCAAGATCATGAGCGGTGAGGTCCCCTCCACGGAGGACCTGGTCAATCTGCTGCCCGCCATCCTCTCGCCTGGAGCCCTTGTAGTCGGTGTGGTCTGCGCAGCAATACTGCGCCGGCACGTTGGCCCGGGCGAGGGGGCAGTGCAATGGATGAACCGGCTAATAGCCTTCGCCTCCCGGGGGAACCATGTTTCCCCCACGCACTACGTGCCGGAGAGCGATGCAGCCGCCCGCGTCACTGCCATACTCAGCAGCCTCACTGTAACCCAGCTCCTGAGGCGACTGCATCAGTGGATAAGCTCGGAGTGTACCACTCCATGCTCCGGTTCCTGGCTAAGGGACATCTGGGACTGGATATGCGAGGTGCTGAGCGACTTTAAGACCTGGCTGAAAGCCAAGCTCATGCCACAACTGCCTGGGATTCCCTTTGTGTCCTGCCAGCGCGGGTATAGGGGGGTCTGGCGAGGAGACGGCATTATGCACACTCGCTGCCACTGTGGAGCTGAGATCACTGGACATGTCAAAAACGGGACGATGAGGATCGTCGGTCCTAGGACCTGCAGGAACATGTGGAGTGGGACGTTCCCCATTAACGCCTACACCACGGGCCCCTGTACTCCCCTTCCTGCGCCGAACTATAAGTTCGCGCTGTGGAGGGTGTCTGCAGAGGAATACGTGGAGATAAGGCGGGTGGGGGACTTCCACTACGTATCGGGTATGACTACTGACAATCTTAAATGCCCGTGCCAGATCCCATCGCCCGAATTTTTCACAGAATTGGACGGGGTGCGCCTACATAGGTTTGCGCCCCCTTGCAAGCCCTTGCTGCGGGAGGAGGTATCATTCAGAGTAGGACTCCACGAGTACCCGGTGGGGTCGCAATTACCTTGCGAGCCCGAACCGGACGTAGCCGTGTTGACGTCCATGCTCACTGATCCCTCCCATATAACAGCAGAGGCGGCCGGGAGAAGGTTGGCGAGAGGGTCACCCCCTTCTATGGCCAGCTCCTCGGCCAGCCAGCTGTCCGCTCCATCTCTCAAGGCAACTTGCACCGCCAACCATGACTCCCCTGACGCCGAGCTCATAGAGGCTAACCTCCTGTGGAGGCAGGAGATGGGCGGCAACATCACCAGGGTTGAGTCAGAGAACAAAGTGGTGATTCTGGACTCCTTCGATCCGCTTGTGGCAGAGGAGGATGAGCGGGAGGTCTCCGTACCCGCAGAAATTCTGCGGAAGTCTCGGAGATTCGCCCGGGCCCTGCCCGTTTGGGCGCGGCCGGACTACAACCCCCCGCTAGTAGAGACGTGGAAAAAGCCTGACTACGAACCACCTGTGGTCCATGGCTGCCCGCTACCACCTCCACGGTCCCCTCCTGTGCCTCCGCCTCGGAAAAAGCGTACGGTGGTCCTCACCGAATCAACCCTATCTACTGCCTTGGCCGAGCTTGCCACCAAAAGTTTTGGCAGCTCCTCAACTTCCGGCATTACGGGCGACAATACGACAACATCCTCTGAGCCCGCCCCTTCTGGCTGCCCCCCCGACTCCGACGTTGAGTCCTATTCTTCCATGCCCCCCCTGGAGGGGGAGCCTGGGGATCCGGATCTCAGCGACGGGTCATGGTCGACGGTCAGTAGTGGGGCCGACACGGAAGATGTCGTGTGCTGCTCAATGTCTTATTCCTGGACAGGCGCACTCGTCACCCCGTGCGCTGCGGAAGAACAAAAACTGCCCATCAACGCACTGAGCAACTCGTTGCTACGCCATCACAATCTGGTGTATTCCACCACTTCACGCAGTGCTTGCCAAAGGCAGAAGAAAGTCACATTTGACAGACTGCAAGTTCTGGACAGCCATTACCAGGACGTGCTCAAGGAGGTCAAAGCAGCGGCGTCAAAAGTGAAGGCTAACTTGCTATCCGTAGAGGAAGCTTGCAGCCTGACGCCCCCACATTCAGCCAAATCCAAGTTTGGCTATGGGGCAAAAGACGTCCGTTGCCATGCCAGAAAGGCCGTAGCCCACATCAACTCCGTGTGGAAAGACCTTCTGGAAGACAGTGTAACACCAATAGACACTACCATCATGGCCAAGAACGAGGTTTTCTGCGTTCAGCCTGAGAAGGGGGGTCGTAAGCCAGCTCGTCTCATCGTGTTCCCCGACCTGGGCGTGCGCGTGTGCGAGAAGATGGCCCTGTACGACGTGGTTAGCAAGCTCCCCCTGGCCGTGATGGGAAGCTCCTACGGATTCCAATACTCACCAGGACAGCGGGTTGAATTCCTCGTGCAAGCGTGGAAGTCCAAGAAGACCCCGATGGGGTTCTCGTATGATACCCGCTGTTTTGACTCCACAGTCACTGAGAGCGACATCCGTACGGAGGAGGCAATTTACCAATGTTGTGACCTGGACCCCCAAGCCCGCGTGGCCATCAAGTCCCTCACTGAGAGGCTTTATGTTGGGGGCCCTCTTACCAATTCAAGGGGGGAAAACTGCGGCTACCGCAGGTGCCGCGCGAGCGGCGTACTGACAACTAGCTGTGGTAACACCCTCACTTGCTACATCAAGGCCCGGGCAGCCTGTCGAGCCGCAGGGCTCCAGGACTGCACCATGCTCGTGTGTGGCGACGACTTAGTCGTTATCTGTGAAAGTGCGGGGGTCCAGGAGGACGCGGCGAGCCTGAGAGCCTTCACGGAGGCTATGACCAGGTACTCCGCCCCCCCCGGGGACCCCCCACAACCAGAATACGACTTGGAGCTTATAACATCATGCTCCTCCAACGTGTCAGTCGCCCACGACGGCGCTGGAAAGAGGGTCTACTACCTTACCCGTGACCCTACAACCCCCCTCGCGAGAGCCGCGTGGGAGACAGCAAGACACACTCCAGTCAATTCCTGGCTAGGCAACATAATCATGTTTGCCCCCACACTGTGGGCGAGGATGATACTGATGACCCATTTCTTTAGCGTCCTCATAGCCAGGGATCAGCTTGAACAGGCTCTTAACTGTGAGATCTACGGAGCCTGCTACTCCATAGAACCACTGGATCTACCTCCAATCATTCAAAGACTCCATGGCCTCAGCGCATTTTCACTCCACAGTTACTCTCCAGGTGAAATCAATAGGGTGGCCGCATGCCTCAGAAAACTTGGGGTCCCGCCCTTGCGAGCTTGGAGACACCGGGCCCGGAGCGTCCGCGCTAGGCTTCTGTCCAGAGGAGGCAGGGCTGCCATATGTGGCAAGTACCTCTTCAACTGGGCAGTAAGAACAAAGCTCAAACTCACTCCAATAGCGGCCGCTGGCCGGCTGGACTTGTCCGGTTGGTTCACGGCTGGCTACAGCGGGGGAGACATTTATCACAGCGTGTCTCATGCCCGGCCCCGCTGGTTCTGGTTTTGCCTACTCCTGCTCGCTGCAGGGGTAGGCATCTACCTCCTCCCCAACCGATGAAGGTTGGGGTAAACACTCCGGCCTCTTAGGCCATTTCCTGTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTCTTTTTTTTTTTTTTTTTCCTTTTTTTTTTTTTTTTTTTTCTTTCCTTCTTTTTTCCTTTCTTTTCCTTCCTTCTTTAATGGTGGCTCCATCTTAGCCCTAGTCACGGCTAGCTGTGAAAGGTCCGTGAGCCGCATGACTGCAGAGAGTGCTGATACTGGCCTCTCTGCAGATCATGT'

const features = [
                    // {cds_start:342,	cds_end:914,	product:'core protein'},
                    // {cds_start:915,	cds_end:	1490,	product:'envelope protein E1'},
                    // {cds_start:1491,	cds_end:	2579,	product:'envelope protein E2'},
                    // {cds_start:2580,	cds_end:	2768,	product:'protein p7'},
                    // {cds_start:2769,	cds_end:	3419,	product:'nonstructural protein NS2'},
                    {cds_start:3420,	cds_end:	5312,	product:'protease/helicase protein NS3', gene:'NS3'},
                    // {cds_start:5313,	cds_end:	5474,	product:'nonstructural protein NS4A'},
                    // {cds_start:5475,	cds_end:	6257,	product:'nonstructural protein NS4B'},
                    {cds_start:6258,	cds_end:	7601,	product:'nonstructural protein NS5A', gene:'NS5A'},
                    {cds_start:7602,	cds_end:	9374,	product:'RNA-dependent RNA polymerase NS5B', gene:'NS5B'}
                ]

const PolymorphismsVisual = ( { data=null, type=null } ) => {
    console.log(data)
    const [selectedFeature, setSelectedFeature] = useState(null);
    const [selectedPolymorphism, setSelectedPolymorphisms] = useState(null)
    if (!Array.isArray(data) || data.length === 0) {
        return <div>No data found...</div>; // or a loader / empty state
    }

    
    const min = 1;
    const max = alignment.length;
    const range = max - min;
    const positions_tmp = Array.from(new Set([].concat(...features.map(f => [f.cds_start])))).sort((a, b) => a - b);
    const positions = [min, ...positions_tmp, max]

    // const enrichedFeatures = features.map(feature => {
    //     const nucleotide_positions = mismatches.filter(
    //         pos => pos >= feature.cds_start && pos <= feature.cds_end
    //     );

    //     return {
    //         ...feature,
    //         nucleotide_positions,
    //     };
    // });

    // const nucleotide_positions = mismatches.filter(
    //         pos => pos >= feature.cds_start && pos <= feature.cds_end
    //     );

    const onFeatureClick = (feature) => {
        console.log("FEATURE", features[feature].gene)
        setSelectedFeature(features[feature])

        const polys = data.filter(polymorphism => polymorphism.protein_name == features[feature].gene)
        setSelectedPolymorphisms(polys)
    }


    return (
        <div>
            <NumberLine positions={positions} min={min} range={range} includeLabel={false}/>
            <Features
                features={features}
                min={min}
                range={range}
                selectedFeature={selectedFeature}
                setSelectedFeature={onFeatureClick}
                includeLabel={false}
            />

            {selectedFeature && (
                <div className='selected-feature'>
                    <h5 className='selected-feature-label'>{selectedFeature.product} ({selectedFeature.cds_start} - {selectedFeature.cds_end})</h5>
                    <MutationViewer  
                        reference_sequence={alignment} 
                        // query_sequence={query_alignment_sequence ? [query_alignment_sequence.query_alignment_sequence] : query_aligned_sequences.map(item => item.query_alignment_sequence)}
                        mutations={selectedPolymorphism}
                        start={parseInt(selectedFeature.cds_start)}
                        end={parseInt(selectedFeature.cds_end)}
                        />
                    
                    {/* <AlignmentViewer
                        reference_sequence={alignment} 
                        query_sequence={query_alignment_sequence ? [query_alignment_sequence.query_alignment_sequence] : query_aligned_sequences.map(item => item.query_alignment_sequence)}
                        nucleotidePositions={selectedFeature.nucleotide_positions}
                        start={parseInt(selectedFeature.cds_start)}
                        end={parseInt(selectedFeature.cds_end)}   
                    /> */}
                </div>
            )}

        </div>
        // <table className="table table-striped table-bordered table-font-12">
        //     <thead>
        //         <tr>
        //             <th>Gene</th>
        //             <th>Polymorphism</th>
        //             <th>Type</th>
        //             <th>Number of Mutations</th>
        //         </tr>
        //     </thead>
        //     <tbody>
                
        //         {data.map((polymorphism, i) => (
        //             <tr key={i} id={i}>
        //                <td>{polymorphism.signature_id.split(':')[0]}</td>
        //                 <td><Link className='gdb-link' to={`/polymorphism/${polymorphism.signature_id}`}>{polymorphism.signature_id.split(':')[1]}</Link></td>
        //                 <td>{polymorphism.signature_kind}</td>
        //                 <td>{polymorphism.signature_count}</td>
        //             </tr>
        //         ))}
        //     </tbody>
        // </table>
    );
};

export default PolymorphismsVisual;
